### ISSUE TITLE
Support for mobile network connections

### ISSUE THREAD

**Issue by cao-jacky** [wowczarek/ptpd#20]
I have PTPd running on an edge server and I want to sync the time of a smartphone to that edge server, to measure various network metrics. The software works fine with WiFi, but once I transition to a 4G/5G network, the packets from the master (server) are not seen by the slave (phone), even if I point with an IP with unicast. If I reverse the roles, the server is able to find the initial packet from the master phone, but then no synchorinsation happens.

I'm guessing that PTPd doesn't work for mobile networks, since the protocol was mainly designed for Ethernet (?), and includes an Ethernet II frame which is missing from packets sent over a 4G/5G network?

Am I missing something with the implementation? Or is deployment on a cellular network not supported at all?

**Comment by wowczarek** [comment]
Hi there - better late than never!

There is nothing specific in PTPd that would prevent it from working on a non-Ethernet interface, in fact it specifically supports interfaces that do not use Ethernet as layer 2, so things like ppp and various other tunnels.

When you say you are attempting to do this over mobile, you also mean over the Internet, right? As in your edge server is sitting on a public IP? Or are you doing this in a test lab, with private 4G/5G?

It's not that it won't work over mobile connections, but multicast, at least IPv4 PTP multicast, will not work over the Internet. Unicast should work fine, but then again you don't get a public IPv4 address over 4G, it will be a private IP behind NAT. Unicast negotiation (telecom profile) should work though, if your client can support this. Manual unicast where you configure the slave IPs on the master and vice versa, will not work because the mobile device is behind NAT. But unicast negotiation should be able to deal with this.

Thanks,
Wojciech

**Comment by cao-jacky** [comment]
Hi, haha yeah! Thanks for your reply! 

My testing is on a university research mobile network, so a testlab scenario. I actually found the solution last week - it was just a matter of the parameters required for the command. 

Originally, I was just using the standard command with unicast pointing in each direction of slave and master, so:
Edge PC:
`sudo ./src/ptpd -C -L -m -V -i Edge_Interface -u Smartphone_Address`

Smartphone:
`./src/ptpd -C -m -V -i Smartphone_Interface -L -u Edge_Address`

The solution in the end was to specifically tell the smartphone to use the socket transport UDP IPv4 
Smartphone:
`./src/ptpd -C -m -V -i Smartphone_Interface -L -u Edge_Address  --ptpengine:transport_implementation=socket_udpv4`

The edge can use the same command and the phone is then able to negotiate with the edge on who is master and slave. 

Hopefully this will help anybody else in the future! Again, thanks for your reply!
